# Generated by Django 5.2 on 2026-06-23 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveIntegerField(unique=True)),
                ('year', models.CharField(max_length=20)),
                ('episodes', models.PositiveIntegerField()),
                ('image', models.CharField(max_length=255)),
                ('link', models.URLField(max_length=500)),
                ('desc', models.TextField()),
            ],
            options={
                'ordering': ['num'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(max_length=150)),
                ('role_name', models.CharField(max_length=150)),
                ('image', models.CharField(max_length=255)),
                ('wikipedia', models.URLField(blank=True, max_length=500)),
                ('role_info', models.TextField()),
                ('role_type', models.CharField(choices=[('protagonist', 'Qəhrəman'), ('antagonist', 'Antagonist')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('seasons', models.ManyToManyField(blank=True, related_name='persons', to='api.season')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SliderSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=10)),
                ('link', models.URLField(max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('season', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slide', to='api.season')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LikedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_items', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to='api.person')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'person')},
            },
        ),
        migrations.CreateModel(
            name='BasketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_items', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_basket_of', to='api.person')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'person')},
            },
        ),
    ]
