# Generated by Django 5.2 on 2026-06-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option_a', models.CharField(max_length=300)),
                ('option_b', models.CharField(max_length=300)),
                ('option_c', models.CharField(max_length=300)),
                ('option_d', models.CharField(max_length=300)),
                ('correct', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('difficulty', models.CharField(choices=[('easy', 'Asan'), ('medium', 'Orta'), ('hard', 'Çətin')], default='medium', max_length=10)),
                ('category', models.CharField(choices=[('characters', 'Personajlar'), ('events', 'Hadisələr'), ('family', 'Koçovalı Ailəsi'), ('enemies', 'Düşmənlər'), ('romance', 'Sevgi Xətləri'), ('general', 'Ümumi')], default='general', max_length=20)),
                ('explanation', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['difficulty', 'category'],
            },
        ),
    ]
